import numpy as np
zeroes = np.zeros(10)
print(zeroes)
vowels = np.array(['a','e','i','o','u'])
print(vowels)
ones = np.ones((2,5),dtype = 'int')
print(ones)
a = np.array([[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]])
print(a)
b= np.arange(4,64,4,'float').reshape(3,5)
print(b)
print(zeroes.shape,zeroes.size,zeroes.dtype,zeroes.ndim,zeroes.itemsize)
print(vowels.shape,vowels.size,vowels.dtype,vowels.ndim,vowels.itemsize)
print(ones.shape,ones.size,ones.dtype,ones.ndim,ones.itemsize)
print(a.shape,a.size,a.dtype,a.ndim,a.itemsize)
print(b.shape,b.size,b.dtype,b.ndim,b.itemsize)
print(ones.reshape(10,))
print(vowels[1],vowels[2])
print(a[1],a[2])
print(a[:,1:2],a[:,0:1])
print(a[1:3,0:1])
print(vowels[::-1])
print(ones/3)
print(ones.transpose())
print(b.transpose())
